### ISSUE TITLE
本地部署中的报错请教 

### ISSUE THREAD

**Issue by jinmo170503** [imClumsyPanda/langchain-ChatGLM#124]
您好，在本地运行langchain-ChatGLM过程中，环境及依赖的包都已经满足条件，但是运行webui.py,报错如下（运行cli_demo.py报错类似），请问是哪里出了错呢？盼望您的回复，谢谢！
Traceback (most recent call last):
File "webui.py", line 1, in
import gradio as gr
File "E:\Anaconda\envs\py3.8\lib\site-packages\gradio_init_.py", line 3, in
import gradio.components as components
File "E:\Anaconda\envs\py3.8\lib\site-packages\gradio\components.py", line 26, in
import matplotlib.figure
File "E:\Anaconda\envs\py3.8\lib\site-packages\matplotlib_init_.py", line 161, in
from . import _api, _version, cbook, _docstring, rcsetup
File "E:\Anaconda\envs\py3.8\lib\site-packages\matplotlib\rcsetup.py", line 27, in
from matplotlib.colors import Colormap, is_color_like
File "E:\Anaconda\envs\py3.8\lib\site-packages\matplotlib\colors.py", line 51, in
from PIL import Image
File "E:\Anaconda\envs\py3.8\lib\site-packages\PIL\Image.py", line 103, in
from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by muyi151** [comment]
相同的问题，哪位可以回答一下？

**Comment by tomFoxxxx** [comment]
更新matplotlib版本试试
