### ISSUE TITLE
是否可以像清华原版跑在8G一以下的卡？

### ISSUE THREAD

**Issue by diyyong** [imClumsyPanda/langchain-ChatGLM#16]
是否可以像清华原版跑在8G一以下的卡？我的8G卡爆显存了🤣🤣🤣

**Comment by imClumsyPanda** [comment]
可以参考一下这个解决方案 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383

**Comment by diyyong** [comment]
刚看了一下，他用了清华的代码，他的代码加载完也需要13G的显存，我今天的想法是用清华的量化版，还在下载模型，感谢你们。

**Comment by diyyong** [comment]
十分感谢你们的帮助。用量化包+https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383， 已经成功运行起来了，可惜我的8G显存太小，只能回答一个问题，还是得换个大点的。

**Comment by diyyong** [comment]
十分感谢你们的帮助。用量化包+https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383%EF%BC%8C ， 已经成功运行起来了，可惜我的8G显存太小，只能回答一个问题，还是得换个大点的。

**Comment by imClumsyPanda** [comment]
后面我会增加一下清理gpu缓存的代码，在每次query执行完成后执行，可能对显存控制会有帮助

**Comment by diyyong** [comment]
这样就太赞了👍👍👍

**Comment by imClumsyPanda** [comment]
已在 chatglm_llm.py 中新增 torch_gc 函数，实现每次调用模型生成问答后清理显存。

**Comment by imClumsyPanda** [comment]
昨晚提交了更新后的代码，有效减少2-3轮提问后可能存在内存爆掉的情况。

**Comment by Risingsun-git** [comment]
**提问第一个问题后，报错RuntimeError: Library cudart is not initialized**是什么原因，怎么解决，请教。
详细报错信息：
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "knowledge_based_chatglm.py", line 117, in <module>
    resp, history = get_knowledge_based_answer(query=query,
  File "knowledge_based_chatglm.py", line 103, in get_knowledge_based_answer
    result = knowledge_chain({"query": query})
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py", line 110, in _call
    answer = self.combine_documents_chain.run(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/combine_documents/base.py", line 56, in _call
    output, extra_return_dict = self.combine_docs(docs, **other_keys)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/combine_documents/stuff.py", line 89, in combine_docs
    return self.llm_chain.predict(**inputs), {}
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 324, in _generate
    text = self._call(prompt, stop=stop)
  File "/home/mengxy/langchain-ChatGLM-master/chatglm_llm.py", line 37, in _call
    response, _ = model.chat(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 1253, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 1158, in forward
    transformer_outputs = self.transformer(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 971, in forward
    layer_ret = layer(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 612, in forward
    attention_outputs = self.attention(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 437, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 340, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 53, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 239, in extract_weight_to_half
    func(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/kernels/base.py", line 36, in _prepare_func
    curr_device = cudart.cudaGetDevice()
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "knowledge_based_chatglm.py", line 117, in <module>
    resp, history = get_knowledge_based_answer(query=query,
  File "knowledge_based_chatglm.py", line 103, in get_knowledge_based_answer
    result = knowledge_chain({"query": query})
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py", line 110, in _call
    answer = self.combine_documents_chain.run(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/combine_documents/base.py", line 56, in _call
    output, extra_return_dict = self.combine_docs(docs, **other_keys)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/combine_documents/stuff.py", line 89, in combine_docs
    return self.llm_chain.predict(**inputs), {}
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/langchain/llms/base.py", line 324, in _generate
    text = self._call(prompt, stop=stop)
  File "/home/mengxy/langchain-ChatGLM-master/chatglm_llm.py", line 37, in _call
    response, _ = model.chat(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 1253, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 1158, in forward
    transformer_outputs = self.transformer(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 971, in forward
    layer_ret = layer(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 612, in forward
    attention_outputs = self.attention(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/modeling_chatglm.py", line 437, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 340, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 53, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027/quantization.py", line 239, in extract_weight_to_half
    func(
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/kernels/base.py", line 36, in _prepare_func
    curr_device = cudart.cudaGetDevice()
  File "/home/anaconda3/envs/py38_chat/lib/python3.8/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized

**Comment by zhaoweihan2017** [comment]
> RuntimeError: Library cudart is not initialized
您好，请问解决了吗？我也遇到类似的问题。

**Comment by wyxscir** [comment]
> RuntimeError: Library cudart is not initialized

conda install cudatoolkit=11.7 -c nvidia
重新安装一下cuda就可以了
