### ISSUE TITLE
AttributeError: 'Chatbot' object has no attribute 'value'

### ISSUE THREAD

**Issue by AnitaSherry** [imClumsyPanda/langchain-ChatGLM#177]
Traceback (most recent call last):
  File "/home/heyiheng/work/langchain/langchain-ChatGLM/webui.py", line 155, in <module>
    chatbot = gr.Chatbot([[None, init_message], [None, model_status.value]],
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/components.py", line 3862, in __init__
    IOComponent.__init__(
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/components.py", line 185, in __init__
    else self.postprocess(initial_value)
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/components.py", line 3908, in postprocess
    y[i] = (self.md.render(message), self.md.render(response))
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/markdown_it/main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/markdown_it/main.py", line 250, in parse
    raise TypeError(f"Input data should be a string, not {type(src)}")
TypeError: Input data should be a string, not <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heyiheng/work/langchain/langchain-ChatGLM/webui.py", line 149, in <module>
    with gr.Blocks(css=block_css) as demo:
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/blocks.py", line 1097, in __exit__
    self.config = self.get_config_file()
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/blocks.py", line 1073, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "/home/young/anaconda3/envs/sakura/lib/python3.10/site-packages/gradio/components.py", line 3875, in get_config
    "value": self.value,
AttributeError: 'Chatbot' object has no attribute 'value'

**Comment by imClumsyPanda** [comment]
请问gradio版本是？

02 ***@***.***>于2023年4月26日 周三17:18写道：

**Comment by AnitaSherry** [comment]
更换了gradio版本，解决了
