### ISSUE TITLE
在mac m2max上抛出了ValueError: 150001 is not in list这个异常

### ISSUE THREAD

**Issue by wjh177** [imClumsyPanda/langchain-ChatGLM#19]
我把chatglm_llm.py加载模型的代码改成如下
` model_path = 'chatglm-6b'
    max_token: int = 2048
    temperature: float = 0.1
    top_p = 0.9
    history = []
    tokenizer = AutoTokenizer.from_pretrained(
        model_path,
        trust_remote_code=True
    )
    model = (
        AutoModel.from_pretrained(
            model_path,
            trust_remote_code=True)
        .half().to('mps')
    )`

**Comment by wjh177** [comment]
`Traceback (most recent call last):
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/conversational_retrieval/base.py", line 83, in _call
    answer, _ = self.combine_docs_chain.combine_docs(docs, **new_inputs)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 89, in combine_docs
    return self.llm_chain.predict(**inputs), {}
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 324, in _generate
    text = self._call(prompt, stop=stop)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/chatglm_llm.py", line 37, in _call
    response, updated_history = self.model.chat(
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/wengjh/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1255, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/Users/wengjh/Desktop/code/model/langchain-ChatGLM/venv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/wengjh/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1091, in prepare_inputs_for_generation
    mask_positions = [seq.index(mask_token) for seq in seqs]
  File "/Users/wengjh/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1091, in <listcomp>
    mask_positions = [seq.index(mask_token) for seq in seqs]
ValueError: 150001 is not in list`

**Comment by wjh177** [comment]
好的 我先排查下

**Comment by imClumsyPanda** [comment]
我在使用m1 mac的过程中是遇到`NotImplementedError: Unknown device for graph fuser`的报错，经搜索是因为macOS 13.3系统不兼容的问题。

不知道你遇到的问题和这个是否相关

**Comment by wjh177** [comment]
好的 其实目前还没有解决 我文本内容已经替换成一串阿拉伯数字还是不行

**Comment by xuexuetong1993** [comment]
词表长度变了 ，150001  - 20000 就行了

**Comment by honglianglv** [comment]
> 词表长度变了 ，150001 - 20000 就行了
我也遇到这个错误了，能说得稍微详细一点吗？ 词表长度具体怎么改，多谢啦。
我试过改 “max_token: int = 160000” 没有用

**Comment by xufengnian** [comment]
这个报错是因为，ChatGLM-6B模型在4月7日左右更新了，去抱脸下载最新的py文件替换一下就行

**Comment by heccxixi** [comment]
> 这个报错是因为，ChatGLM-6B模型在4月7日左右更新了，去抱脸下载最新的py文件替换一下就行

可是我下载了新的config和.py还是出现了报错
 mask_positions = [seq.tolist().index(mask_token) for seq in input_ids]
ValueError: 130000 is not in list

**Comment by imClumsyPanda** [comment]
模型文件也有更新 应该是第一个和最后一个
建议用 git pull 更新

heccxixi ***@***.***>于2023年4月12日 周三18:22写道：
