### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by PPGGG** [imClumsyPanda/langchain-ChatGLM#198]
When i tried to use the non-streaming, `ValueError: too many values to unpack (expected 2)` error came out.

**Comment by imClumsyPanda** [comment]
will fix in recent new versions

**Comment by imClumsyPanda** [comment]
Already fixed in v0.1.9

**Comment by rickbraddy-pharma** [comment]
I just install LanChain build 174.  Still seeing this:

**Generate a Python class and unit test program that calculates the first 100 Fibonaci numbers and prints them out. Be sure to provide comments at the start of each module, function or major block of code.**

Traceback (most recent call last):
  File "/home/ec2-user/dev/langchain/langchain/agents/conversational_chat/output_parser.py", line 21, in parse
    cleaned_output, _ = cleaned_output.split("```")
ValueError: too many values to unpack (expected 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/dev/botwork/team/teambot.py", line 127, in <module>
    creation = creationAgent.run(input=prompt1)
  File "/home/ec2-user/dev/langchain/langchain/chains/base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "/home/ec2-user/dev/langchain/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/home/ec2-user/dev/langchain/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/ec2-user/dev/langchain/langchain/agents/agent.py", line 947, in _call
    next_step_output = self._take_next_step(
  File "/home/ec2-user/dev/langchain/langchain/agents/agent.py", line 773, in _take_next_step
    raise e
  File "/home/ec2-user/dev/langchain/langchain/agents/agent.py", line 762, in _take_next_step
    output = self.agent.plan(
  File "/home/ec2-user/dev/langchain/langchain/agents/agent.py", line 444, in plan
    return self.output_parser.parse(full_output)
  File "/home/ec2-user/dev/langchain/langchain/agents/conversational_chat/output_parser.py", line 36, in parse
    raise OutputParserException(f"Could not parse LLM output: {text}") from e
langchain.schema.OutputParserException: Could not parse LLM output: ```json
{
    "action": "Final Answer",
    "action_input": "Here's a Python class and a unit test program for calculating and printing the first 100 Fibonacci numbers, with comments added for clarity:\n\n```python\nimport unittest\n\n\nclass Fibonacci:\n    def __init__(self, n=100):\n        self.n = n\n        self.fibonacci_sequence = self.generate_fibonacci()\n\n    def generate_fibonacci(self):\n        sequence = [0, 1]\n        for i in range(2, self.n):\n            sequence.append(sequence[-1] + sequence[-2])\n        return sequence\n\n    def print_fibonacci(self):\n        for number in self.fibonacci_sequence:\n            print(number)\n\n\nclass TestFibonacci(unittest.TestCase):\n    def test_generate_fibonacci(self):\n        fib = Fibonacci(10)\n        self.assertEqual(fib.fibonacci_sequence, [0, 1, 1, 2, 3, 5, 8, 13, 21, 34])\n\n\nif __name__ == '__main__':\n    unittest.main()\n```\n\nThis code includes a Fibonacci class for generating and printing the first 100 Fibonacci numbers (or any other number specified). It also provides a unit test to ensure the correctness of the Fibonacci sequence generation."
}
```
