### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by zjzoze** [imClumsyPanda/langchain-ChatGLM#222]
**local variable 'torch' referenced before assignment**
更新最新版本后，出现local variable 'torch' referenced before assignment错误，python3.8-3.9都试过，4天前clone的版本没问题。

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): text2vec-large-chinese
- 操作系统及版本 / WSL UBUNTU 22.04:
- Python 版本 / Python version:3.8.16

**Comment by zjzoze** [comment]
模型已成功重新加载，可以开始对话，或从右侧选择模式后开始对话
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/gradio/blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/chatglm/lib/python3.8/site-packages/gradio/utils.py", line 488, in async_iteration
    return next(iterator)
  File "./webui.py", line 50, in get_answer
    for resp, history in local_doc_qa.llm._call(query, history,
  File "/home/langchain-ChatGLM/models/chatglm_llm.py", line 77, in _call
    torch_gc(DEVICE)
  File "/home/langchain-ChatGLM/utils/__init__.py", line 5, in torch_gc
    if torch.cuda.is_available():
UnboundLocalError: local variable 'torch' referenced before assignment

**Comment by imClumsyPanda** [comment]
今天下午已针对该报错更新了代码，请尝试更新代码后，再次测试是否还存在该问题，谢谢。

**Comment by zjzoze** [comment]
已被修复，而且效果好了很多，谢谢
