### ISSUE TITLE
[BUG]  加载chatglm模型报错：'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by ruitaomu** [imClumsyPanda/langchain-ChatGLM#398]
**问题描述 / Problem Description**
加载chatglm模型报错：'NoneType' object has no attribute 'message_types_by_name'，导致加载模型失败

**复现问题的步骤 / Steps to Reproduce**
执行 python webui.py或重新加载模型时报错（见最后一行）：
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)/modeling_chatglm.py: 100%|███████████████████████████████████████████████████| 59.4k/59.4k [00:00<00:00, 493kB/s]
Downloading (…)main/quantization.py: 100%|███████████████████████████████████████████████████| 31.0k/31.0k [00:00<00:00, 215kB/s]
ERROR 2023-05-17 18:34:56,154-1d: 'NoneType' object has no attribute 'message_types_by_name'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit [a5417e1](https://github.com/imClumsyPanda/langchain-ChatGLM/commit/a5417e1cf56ca6754cbdfe629afb282ee4bbf48a)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B（v1.1.0或v0.1.0都报错）
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：任何
- 操作系统及版本 / Operating system and version: Ubuntu Linux 18_04 LTS
- Python 版本 / Python version: 3.10.9
- 其他相关环境信息 / Other relevant environment information: CUDA

**Comment by etermis** [comment]
same problem here, fixed by update protobuf to 3.19.6

Traceback (most recent call last):
  File "/mnt/workspace/langchain-ChatGLM/webui.py", line 7, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/usr/local/lib/python3.10/dist-packages/accelerate/tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/event_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/summary_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import histogram_pb2 as tensorboard_dot_compat_dot_proto_dot_histogram__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/histogram_pb2.py", line 21, in <module>
    _HISTOGRAMPROTO = DESCRIPTOR.message_types_by_name['HistogramProto']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by ONLY-yours** [comment]
> 

dude, you are so nice! thats works for me, thank you

**Comment by quanzhang2020** [comment]
+1

**Comment by ruitaomu** [comment]
Thanks, it works for me.

**Comment by junxin367** [comment]
更新protobuf版本解决问题
pip install --upgrade protobuf==3.19.6
