### ISSUE TITLE
Error reported during startup

### ISSUE THREAD

**Issue by zhubao315** [imClumsyPanda/langchain-ChatGLM#443]
Traceback (most recent call last):
  File "webui.py", line 5, in <module>
    from chains.local_doc_qa import LocalDocQA
  File "/chatGLM/chains/local_doc_qa.py", line 13, in <module>
    from loader import UnstructuredPaddleImageLoader, UnstructuredPaddlePDFLoader
  File "/chatGLM/loader/__init__.py", line 1, in <module>
    from .image_loader import UnstructuredPaddleImageLoader
  File "/chatGLM/loader/image_loader.py", line 5, in <module>
    from paddleocr import PaddleOCR
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/paddleocr.py", line 25, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by zhubao315** [comment]
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
RUN apt-get install ffmpeg libsm6 libxext6 libgl1 libglib2.0-0 -y && apt-get clean

Just add libgl1 libglib
