### ISSUE TITLE
纯CPU环境下运行cli_demo时报错，提示找不到nvcuda.dll

### ISSUE THREAD

**Issue by ai-ycy** [imClumsyPanda/langchain-ChatGLM#576]
本地部署环境是纯CPU，之前的版本在纯CPU环境下能正常运行，但上传本地知识库经常出现encode问题。今天重新git项目后，运行时出现如下问题，请问该如何解决。

Traceback (most recent call last):
  File "cli_demo.py", line 56, in <module>
    main()
  File "cli_demo.py", line 19, in main
    llm_model_ins = shared.loaderLLM()
  File "D:\project\pyproject\project\langchain-ChatGLM\models\shared.py", line 40, in loaderLLM
    loaderCheckPoint.reload_model()
  File "D:\project\pyproject\project\langchain-ChatGLM\models\loader\loader.py", line 402, in reload_model
    self.model, self.tokenizer = self._load_model(self.model_name)
  File "D:\project\pyproject\project\langchain-ChatGLM\models\loader\loader.py", line 206, in _load_model
    model = LoaderClass.from_pretrained(checkpoint, **params).to(self.llm_device, dtype=float)
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\transformers\dynamic_module_utils.py", line 425, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\transformers\dynamic_module_utils.py", line 305, in get_cached_module_file
    get_cached_module_file(
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\transformers\dynamic_module_utils.py", line 267, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\transformers\dynamic_module_utils.py", line 145, in check_imports
    importlib.import_module(imp)
  File "D:\python\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\cpm_kernels\library\__init__.py", line 2, in <module>
    from . import cuda
  File "D:\project\pyproject\env\langchain-ChatGLM\lib\site-packages\cpm_kernels\library\cuda.py", line 7, in <module>
    cuda = Lib.from_lib("cuda", ctypes.WinDLL("nvcuda.dll"))
  File "D:\python\py38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by bk007lz** [comment]
如何解决的这个问题？

**Comment by ai-ycy** [comment]
> 如何解决的这个问题？

model_config.py文件里面的chatglm-6b模型文件路径修改为下载好的本地路径就好了
