### ISSUE TITLE
[BUG] AssertionError 

### ISSUE THREAD

**Issue by shadowbox-cash** [imClumsyPanda/langchain-ChatGLM#658]
**问题描述 / Problem Description**
Embedding 模型使用默认的text2vec是运行正常的，但是我使用m3e-base，就报错AssertionError，
运行时没有报错，只是warning：
Loaded the model in 7.73 seconds.
WARNING 2023-06-17 13:15:43,334-1d: No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.

用户一问问题，就报错信息如下：
 Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/blocks.py", line 1090, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/root/langchain-ChatGLM/webui.py", line 58, in get_answer
    for resp, history in local_doc_qa.get_knowledge_based_answer(
  File "/root/langchain-ChatGLM/chains/local_doc_qa.py", line 228, in get_knowledge_based_answer
    related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 221, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/root/langchain-ChatGLM/vectorstores/MyFAISS.py", line 47, in similarity_search_with_score_by_vector
    scores, indices = self.index.search(vector, k)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/faiss/class_wrappers.py", line 329, in replacement_search
    assert d == self.d
AssertionError

**Comment by imClumsyPanda** [comment]
是因为构建知识库的embedding模型需要与检索时所用的模型一致，修改embedding模型后，需要在重新用新选的embedding模型构建知识库后重新提问才行。
