### ISSUE TITLE
[BUG] 加载其他embedding模型，就无法上传文件向量化

### ISSUE THREAD

**Issue by Qmymy** [imClumsyPanda/langchain-ChatGLM#690]
WARNING 2023-06-21 15:14:51,493-1d: No sentence-transformers model found with name C:\Users\Qmy/.cache\torch\sentence_transformers\moka-ai_m3e-base. Creating a new one with MEAN pooling.
WARNING 2023-06-21 15:14:55,429-1d: The dtype of attention mask (torch.int64) is not bool
{'answer': '你好👋！我是人工智能助手 ChatGLM-6B，很高兴见到你，欢迎问我任何问题。'}

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Qmy\Desktop\langchain-ChatGLM-0.1.16\webui.py", line 149, in get_vector_store
    vs_path, loaded_files = local_doc_qa.init_knowledge_vector_store(filelist, vs_path, sentence_size)
  File "C:\Users\Qmy\Desktop\langchain-ChatGLM-0.1.16\chains\local_doc_qa.py", line 205, in init_knowledge_vector_store
    vector_store.add_documents(docs)
  File "E:\langchain-ChatGLM-0.1.16\lib\site-packages\langchain\vectorstores\base.py", line 62, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File 
切换其他embedding模型的时候出现这个问题，貌似断言错误导致不能添加到向量储存中？

**Comment by Qmymy** [comment]
你们能正常使用其他的embedding模型吗？比如m3e的？

**Comment by tmzncty** [comment]
> 你们能正常使用其他的embedding模型吗？比如m3e的？

不能，直接说找不到
ARNING 2023-06-22 09:17:43,414-1d: No sentence-transformers model found with name /home/tmzncty/AI/ernie-3.0-nano-zh. Creating a new one with MEAN pooling.
Some weights of ErnieModel were not initialized from the model checkpoint at /home/tmzncty/AI/ernie-3.0-nano-zh and are newly initialized: ['ernie.pooler.dense.bias', 'ernie.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
WARNING 2023-06-22 09:17:45,017-1d: The dtype of attention mask (torch.int64) is not bool

**Comment by deepblind** [comment]
这个问题和我报告的一样，其实是只能使用联机下载的embedding模型，这个模型先下载然后修改配置也不行。

**Comment by zfanswer** [comment]
> 你们能正常使用其他的embedding模型吗？比如m3e的？

我一直在用m3e的，自己下载的，重建新知识库，提问回答都没问题。v0.1.16

你这个问题不是没法加载其他embedding模型吧，是不是你用text2vec做了一个向量数据库，然后换到m3e来提问报错？
