### ISSUE TITLE
Unrecognized configuration class <class 'transformers_modules.model.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.

### ISSUE THREAD

**Issue by lindiny** [imClumsyPanda/langchain-ChatGLM#707]
(langchain-ChatGlM) E:\AI\langchain-ChatGLM-master>python webui.py
INFO  2023-06-25 22:04:18,164-1d:
loading model config
llm device: cuda
embedding device: cuda
dir: E:\AI\langchain-ChatGLM-master
flagging username: 544e71b0bc0c456c8c1180d6dfef0038

Loading .\model...
Traceback (most recent call last):
  File "E:\AI\langchain-ChatGLM-master\webui.py", line 322, in <module>
    model_status = init_model()
  File "E:\AI\langchain-ChatGLM-master\webui.py", line 103, in init_model
    llm_model_ins = shared.loaderLLM()
  File "E:\AI\langchain-ChatGLM-master\models\shared.py", line 40, in loaderLLM
    loaderCheckPoint.reload_model()
  File "E:\AI\langchain-ChatGLM-master\models\loader\loader.py", line 419, in reload_model
    self.model, self.tokenizer = self._load_model(self.model_name)
  File "E:\AI\langchain-ChatGLM-master\models\loader\loader.py", line 122, in _load_model
    LoaderClass.from_pretrained(checkpoint,
  File "D:\ProgramData\anaconda3\envs\langchain-ChatGlM\lib\site-packages\transformers\models\auto\auto_factory.py", line 470, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.model.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by SaeedBai** [comment]
同问，
我的错误是
ValueError: Unrecognized configuration class <class 'str'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig,
CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig,
LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig,
RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig,
XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by zhiqihuanghhhh** [comment]
同问我的错误是
INFO  2023-07-11 10:07:53,004-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: E:\use\deep\gpt\langchainchat\langchain-ChatGLM
flagging username: 09c0e44238114d98a6bf3a5730362b2e

Loading E:\use\model\6b2...
Traceback (most recent call last):
  File "E:\use\deep\gpt\langchainchat\langchain-ChatGLM\webui.py", line 322, in <module>
    model_status = init_model()
  File "E:\use\deep\gpt\langchainchat\langchain-ChatGLM\webui.py", line 103, in init_model
    llm_model_ins = shared.loaderLLM()
  File "E:\use\deep\gpt\langchainchat\langchain-ChatGLM\models\shared.py", line 40, in loaderLLM
    loaderCheckPoint.reload_model()
  File "E:\use\deep\gpt\langchainchat\langchain-ChatGLM\models\loader\loader.py", line 430, in reload_model
    self.model, self.tokenizer = self._load_model(self.model_name)
  File "E:\use\deep\gpt\langchainchat\langchain-ChatGLM\models\loader\loader.py", line 122, in _load_model
    LoaderClass.from_pretrained(checkpoint,
  File "E:\Anaconda\envs\chain\lib\site-packages\transformers\models\auto\auto_factory.py", line 470, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.6b2.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

Process finished with exit code 1

**Comment by PittYao** [comment]
一样的问题

**Comment by PittYao** [comment]
> 一样的问题

2024-01-02 16:46:01,383 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-02 16:46:01,383 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-chatchat/Langchain-Chatchat/logs
2024-01-02 16:46:08 | INFO | model_worker | Register to controller
2024-01-02 16:46:08 | ERROR | stderr | INFO:     Started server process [1831115]
2024-01-02 16:46:08 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-02 16:46:08 | ERROR | stderr | INFO:     Application startup complete.
2024-01-02 16:46:08 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-01-02 16:46:09 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 746a5d3d ...
2024-01-02 16:46:09 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-01-02 16:46:09 | ERROR | stderr | Traceback (most recent call last):
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-01-02 16:46:09 | ERROR | stderr |     self.run()
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-01-02 16:46:09 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-01-02 16:46:09 | ERROR | stderr |   File "/root/Langchain-chatchat/Langchain-Chatchat/startup.py", line 387, in run_model_worker
2024-01-02 16:46:09 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-01-02 16:46:09 | ERROR | stderr |   File "/root/Langchain-chatchat/Langchain-Chatchat/startup.py", line 215, in create_model_worker_app
2024-01-02 16:46:09 | ERROR | stderr |     worker = ModelWorker(
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-01-02 16:46:09 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 323, in load_model
2024-01-02 16:46:09 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 774, in load_model
2024-01-02 16:46:09 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-01-02 16:46:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 815, in from_pretrained
2024-01-02 16:46:09 | ERROR | stderr |     raise ValueError(
2024-01-02 16:46:09 | ERROR | stderr | ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm3-6b.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
2024-01-02 16:46:09 | ERROR | stderr | Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecAudioConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, InstructBlipConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LlavaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, UMT5Config, ViltConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.
