### ISSUE TITLE
执行webui.py后报错transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by zhengqingwu** [imClumsyPanda/langchain-ChatGLM#900]
INFO  2023-07-20 15:27:47,265-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /home/wzq/langchain-ChatGLM
flagging username: 493b58f9c0614cd7a931f143b37a9f55

Traceback (most recent call last):
  File "webui.py", line 4, in <module>
    from chains.local_doc_qa import LocalDocQA
  File "/home/wzq/langchain-ChatGLM/chains/local_doc_qa.py", line 14, in <module>
    from models.loader.args import parser
  File "/home/wzq/langchain-ChatGLM/models/__init__.py", line 1, in <module>
    from .chatglm_llm import ChatGLMLLMChain
  File "/home/wzq/langchain-ChatGLM/models/chatglm_llm.py", line 6, in <module>
    from transformers.generation.utils import LogitsProcessorList, StoppingCriteriaList
  File "/home/wzq/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..deepspeed import is_deepspeed_zero3_enabled
  File "/home/wzq/.local/lib/python3.8/site-packages/transformers/deepspeed.py", line 38, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/home/wzq/.local/lib/python3.8/site-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

外挂知识库，执行python webui.py后报错以上信息

环境按照要求进行配置的

检查了好久的版本问题，但始终没有解决，希望有大佬能帮忙解决一下

**Comment by hzg0601** [comment]
注释第五、六行试试

**Comment by zhengqingwu** [comment]
> 

是哪个文件的第五六行呢

**Comment by hzg0601** [comment]
chatglm_llm.py

**Comment by hzg0601** [comment]
长时间未更新，暂时关闭

**Comment by zhengqingwu** [comment]
> .好的谢谢
