### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by ifanbin** [imClumsyPanda/langchain-ChatGLM#906]
运行api.py经常与远程主机连接有问题，已经采用本地glm2-6b的本地模型跑，为什么还会有连接远程主机操作？

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\langchain-ChatGLM\api.py", line 407, in <module>
    api_start(args.host, args.port)
  File "D:\ai\langchain-ChatGLM\api.py", line 390, in api_start
    local_doc_qa.init_cfg(
  File "D:\ai\langchain-ChatGLM\chains\local_doc_qa.py", line 204, in init_cfg
    self.embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[embedding_model],
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\huggingface_hub\hf_api.py", line 1675, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\ai\langchain-ChatGLM\venv\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by hzg0601** [comment]
模型加载EMBEDDING_MODEL时仍需联网，如果完全离线需要修改HuggingFaceEmbeddings的代码

**Comment by flowbywind** [comment]
我的是向量模型文件没改为本地路径，所以每次执行网络下载因为网络不好报错。需要修改model_config里向量那个文件embedding_model_dict里text2vec值到本地位置 "text2vec": "/opt/*****/text2vec-large-chinese", 同样LLM的文件也要改到本地路径
