### ISSUE TITLE
langchain-chatglm2 启动报错 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by darvsum** [imClumsyPanda/langchain-ChatGLM#909]
按照项目文档安装、配置后启动报错， 不知什么原因。 请知道的同学指导下。谢谢 
(ll) root@autodl-container-a8e51198ae-191d582b:~/langchain-chatglm# python webui.py 
INFO  2023-07-21 22:01:18,050-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /root/langchain-chatglm
flagging username: 03327c962b384105b98356e45f7daa6d

WARNING: OMP_NUM_THREADS set to 15, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
[2023-07-21 22:01:21,134] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
load_model_config /root/autodl-tmp/chatglm2-6b...
Loading /root/autodl-tmp/chatglm2-6b...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.23s/it]
Loaded the model in 11.53 seconds.
INFO  2023-07-21 22:01:33,250-1d: Load pretrained SentenceTransformer: /root/autodl-tmp/text2vec-large-chinese
WARNING 2023-07-21 22:01:33,251-1d: No sentence-transformers model found with name /root/autodl-tmp/text2vec-large-chinese. Creating a new one with MEAN pooling.
__call:你好
Traceback (most recent call last):
  File "/root/langchain-chatglm/models/base/base.py", line 114, in gen
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/root/langchain-chatglm/models/base/base.py", line 163, in generate_with_callback
    self._generate_answer(**kwargs)
  File "/root/langchain-chatglm/models/chatglm_llm.py", line 100, in _generate_answer
    response, _ = self.checkPoint.model.chat(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 1028, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2648, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
INFO  2023-07-21 22:01:37,835-1d: 模型已成功加载，可以开始对话，或从右侧选择模式后开始对话
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by hzg0601** [comment]
模型默认的加载类型为float16,其只有5位指数位，存在极小的概率会在推理时溢出，一般重新加载可以解决，如果持续报错，请考虑是否加载了错误的模型或使用了量化参数。如果这些都没有解决，请重开此issue
